name: 数据迁移授权
description: 鸿蒙 OpenHarmony 用户数据迁移授权协议
title: "鸿蒙 OpenHarmony 用户数据迁移授权协议"
labels: ["agreed"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 《鸿蒙 OpenHarmony 用户数据迁移授权协议》

        ### 甲方
        
        鸿蒙 OpenHarmony 

  - type: input
    id: user
    attributes:
      label: 乙方
      placeholder: 请填写你的姓名...
    validations:
      required: true

  - type: input
    id: gitee
    attributes:
      label: Gitee 账号
      placeholder: 请填写你的 Gitee 账号...
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ##

        鸿蒙 OpenHarmony 项目组和用户就用户数据迁移事宜，经友好协商，达成如下协议：

        **一、数据迁移目的：甲方为了提升用户体验和数据安全性，需要对用户的个人信息以及与用户相关的项目、问题、拉取请求和代码评审数据等内容进行迁移操作。**

        **二、数据迁移内容：本次数据迁移涉及用户的个人信息以及与用户相关的项目、问题、拉取请求和代码评审数据等内容。**

        **三、数据迁移方式：甲方将采取合适的技术手段，将数据迁移至新的数据存储系统，并在必要时与合作方分享数据，但保证仅在符合法律法规要求的情况下进行数据共享，并与合作方签署保密协议。**

        **四、数据迁移安全保障：甲方将采取适当的安全措施保护用户的个人信息不受未经授权的访问、使用或泄露。**

        **五、数据迁移责任：甲方将尽最大努力保证数据的完整性和准确性，但在数据迁移过程中可能会遇到一些技术问题或延迟，甲方将及时通知用户。**

        **六、用户确认：用户确认已阅读并同意本授权协议，同意甲方按照本协议约定进行数据迁移操作，并承诺提供的个人信息合法、真实、准确和完整。**

        **七、协议变更与终止：甲方有权根据法律法规的要求或为了保护用户及社区的合法权益而修改或终止本授权协议。**

        **八、其他条款：本协议未尽事宜，由甲乙双方友好协商解决。**

        **本授权协议自用户提交到到当前项目之日起生效，至数据迁移完成之日终止。**

  - type: checkboxes
    id: agreement
    attributes:
      label: 授权声明
      options:
        - label: 本人已经阅读并同意《鸿蒙 OpenHarmony 用户数据迁移授权协议》
          required: true